src/main/java/com/github/javafaker/Internet.java
some of the test data contains first and last names with quotation marks and non-ASCII accented characters
=> url and email tests fail with first/last names that have quotation marks and accents

src/main/java/com/github/javafaker/Lorem.java, src/test/java/com/github/javafaker/LoremTest.java
I found myself repeatedly requesting a list containing one word and then getting it from its List. This skips the creation of the List to begin with, allowing clearer test code when only one word is desired.
=> Add a (single) word method to the Lorem generator.

src/main/java/com/github/javafaker/Lorem.java, src/test/java/com/github/javafaker/BeerTest.java, src/test/java/com/github/javafaker/LoremTest.java, src/test/java/com/github/javafaker/NameTest.java
Some notes:
* There is some overlap with `Lorem#fixedString`.
* I modeled the method closely on the ruby faker one, so lower-case alphanumeric characters are returned. Not sure this is the best approach.
* Not sure if `character` should return a `String` instead of a `char`?
* I would have liked to use the much less verbose `new BigInteger(int, random).toString(32)` to generate the string. This was not possible because  `JVMRandom` throws an `UnsupportedOperationException` when `#nextBytes` is invoked by the `BigInteger` constructor.
=> add Lorem#character and Lorem#characters

pom.xml
use maven shade plugin to include this dependency in the java-faker jar, because it is not available from maven central
I tried to add the shade plugin configuration to the `<plugin-management>` section (like the other plugin configuration), but that did not work. I guess it's because the shade plugin is not bound to maven life-cycle by default. (Not sure why the other plugins are in the `<plugin-management>` section, because usually this section is used to configure project builds that inherit from the project.)
By the way: I was able to successfully use java-faker on an android emulator. :)
=> changed snakeyaml to the bmoliveira one to provide support for android

src/main/java/com/github/javafaker/Internet.java
Currently, given certain names that can show up (for example, O'Reilly), if a name has a single quote in it, it'll generate an invalid email address. This removes any single quotes that may be in the name.
=> Remove single quotes from names used in email addresses

src/main/java/com/github/javafaker/service/FakeValuesService.java, src/test/java/com/github/javafaker/integration/FakerIT.java, src/test/java/com/github/javafaker/integration/MostSpecificLocaleIT.java
Closes DiUS/java-faker#125
Fixes a couple of issues.
1) when constructing a new locale like new Locale("pt-br"), the correct file /pt-BR.yml will be loaded.
2) the correct yaml file is returned by language and country code.  loading a new Faker with en_US would return /en.yml and not /en-US.yml
=> Handle legacy-style constructed Locales

src/main/java/com/github/javafaker/Faker.java, src/main/java/com/github/javafaker/service/FakeValuesService.java, src/test/java/com/github/javafaker/AbstractFakerTest.java, src/test/java/com/github/javafaker/FakerTest.java, src/test/java/com/github/javafaker/RandomFakerTest.java, src/test/java/com/github/javafaker/UniversityTest.java, src/test/java/com/github/javafaker/service/FakeValuesServiceTest.java, src/test/java/com/github/javafaker/service/RandomServiceTest.java, src/test/resources/test.yml
resolves DiUS/java-faker#134 (closed PR)
The idea to use arguments in resolve was closely related to something i wanted to do which is to put the power of letterify, numberify and regexify into the YML expression language.  This allows for more complicated expressions that can be sculpted to be more correct without having to write java.
Now you can use something like #{regexify '[45]{2}ABC'} and it will work returning either 45ABC or 55ABC, etc...  This should help in creating more correct phone numbers, area codes, etc...
Any method exposed on Faker, even with arguments will work.
Even #{bothify '##??','true'} will work.  While all arguments are 'strings' in the YML, they are coerced to the appropriate type prior to calling the method in Faker, so this expression will result in …
=> Add arguments to YML directives

src/main/java/com/github/javafaker/Internet.java, src/test/java/com/github/javafaker/InternetTest.java
I originally created the Internet implementation directly from the stimpy/faker project
but it's too slow.  It looped over regexes until it found one.  In a quick test i found it
sometimes looping > 100 times to find a private IP address.
I replaced the implementation with a very fast very direct implementation since we know
exactly why octets are used to create a private address.
The tests run now in 60+ms instead of 2000+ms.
=> Speed up the Internet implementation

README.md, pom.xml
Remove the snake-yaml binaries from the main jar and include
for backwards compatibility sake in the 'deps' jar created by the
maven-shade-plugin.
resolves DiUS/java-faker#130
=> Put snake-yaml binaries into 'deps' shaded jar

src/main/java/com/github/javafaker/Number.java, src/test/java/com/github/javafaker/NumberTest.java
resolves DiUS/java-faker#121
Number#numberBetween and Number#randomDouble exhibited poor behavior when using extremes for
their min/max values.  In the worst case, it would return the same number over and over and in
other cases (maybe this is the worst) it would die.  As a library used to generating fake data,
the library should do its best to not throw errors around min/max ranges, etc., instead
returning usable fake values that best fit the parameters passed in.
This PR fixes the issues with random number generation and a good number of tests were added
to ensure the quality of the randomization by ensuring that 90% of random series are 80% unique.
This should be sufficient for most uses.
Also, the Number class itself was refactored to reuse decimalBetween as the primary number …
=> Fix Number randomization quality and correctness

src/main/java/com/github/javafaker/service/FakeValuesService.java, src/test/java/com/github/javafaker/service/FakeValuesServiceTest.java
Fixes DiUS/java-faker#143
There was an intermittent test failure where the error message would say :
Expected: is "Unable to coerce x to Long via Long(String) constructor."
but: was "Unable to coerce x to Integer via Integer(String) constructor."
The issue is getMethod() returning the methods in a non-deterministic order.
Fixing this could have been easy by simply changing the check to look for Long or Integer but
this would hide a real issue where by methodName(int) called via methodName(Long.MAX_VALUE) would
die even if methodName(long) existed because it would attempt to coerce the arguments
to int ONLY and ignore the long variation.
I altered the logic to attempt to coerce the arguments at the same time the method is located
by name.  This means that methodName(Long.MAX_VALUE) will …
=> Fix method resolution with overloaded methods

src/main/java/com/github/javafaker/Code.java, src/main/java/com/github/javafaker/service/FakeValuesService.java, src/test/java/com/github/javafaker/AbstractFakerTest.java, src/test/java/com/github/javafaker/CodeTest.java, src/test/resources/test.yml
Implement valid ISBN numbers.  The implementation will always return valid ISBN numbers for english speaking books.  There is support
for other countries via overrides in the yml files but the values are not currently set.  Default values are constructed in the
Java so that the functionality doesn't break if we bring over the yml files from the stympy/faker project.
A test is included however to show that the values can be customized via yml if we choose to do so.
Fixes DiUS/java-faker#168
=> Always return valid ISBN Numbers

src/main/java/com/github/javafaker/service/FakeValuesService.java, src/test/java/com/github/javafaker/integration/FakerIT.java, src/test/java/com/github/javafaker/integration/Issue194SlashFormatRegexIT.java, src/test/java/com/github/javafaker/service/FakeValuesServiceTest.java, src/test/resources/test.yml
Handle slash format (ex. /[a-b]+/) regular expressions in .yml files.
This is handled internally in the safeFetch method by converting the statement from the /x/ format to
the #{regexify 'x'} directive format.
=> Fixes #194 handle slash format regex in yml

pom.xml, src/test/java/com/github/javafaker/InternetTest.java, src/test/java/com/github/javafaker/NumberTest.java
remove usage of javax.annotation.Nullable in test, as this transitive test dependency does not exit anymore
=> update test dependency versions

.travis.yml
Recently Travis CI introduced ubuntu:trusty as a default environment. Unfortunately, it has 2 issues which affects this repository:
1) oraclejdk7 is no longer supported due to Oracle's withdrawal. See details: https://github.com/travis-ci/travis-ci/issues/7884 and example failing build: https://travis-ci.org/DiUS/java-faker/jobs/273565200)
2) openjdk7 is supported on trusty, however there is a problem with shading snakeyaml library caused by lack of SunEC provider. See details: https://github.com/docker-library/openjdk/issues/117 and example failing build https://travis-ci.org/DiUS/java-faker/jobs/273565202
=> Step back to ubuntu precise.

src/main/java/com/github/javafaker/Finance.java, src/test/java/com/github/javafaker/FinanceTest.java
This method allows specific credit card types to be returned. This is useful for testing purposes when someone needs to ensure they test only a certain subset of credit cards, e.g Visa and Mastercard, but not AMEX.
Added unit test.
=> Adding overloaded method to allow a specific credit card format to be returned

src/main/java/com/github/javafaker/Internet.java, src/test/java/com/github/javafaker/InternetTest.java
This PR adds a faker for an UUID to the internet faker. Usage:
```
String uuid = faker.internet().uuid()
```
I got the regex used in the test from https://stackoverflow.com/questions/7905929/how-to-test-valid-uuid-guid
=> Add UUID to faker

src/main/java/com/github/javafaker/service/FakeValuesService.java
Hi,
Not sure if it was intentional, or just reminiscent from some older code. I couldn't find any reason for having `StringBuffer` instead of `StringBuilder`, nor any javadocs about threads and synchronization.
I believe it won't cause any regression. And while these two methods (`#numerify` and `#letterHelper`) used `StringBuffer`s, the constructor  uses `StringBuilder`, and other parts of the code also use `StringBuilder`s (e.g. `Code#isbn10`, `FakerIDN#toASCII`, ...).
Quickly created the pull request from GitHub interface, but hopefully Travis CI will build it and confirm it works fine. Found it while using the IDE to find occurrences of these classes in a legacy code at work.
Cheers
Bruno
=> Replace StringBuffer by StringBuilder

src/main/java/com/github/javafaker/DateAndTime.java, src/test/java/com/github/javafaker/DateAndTimeTest.java
Hi!
Thanks for java-faker, saved me some time writing tests this past week.
I think GregorianCalendar's month is 0-based, and in the birthday faker it would result in an error?
This pull request changes the value from 12 to 11. Also removed the unnecessary canonical name for `java.util.Date` which was already imported.
Thanks again
Bruno
=> Use month values between 0-11 for GregorianCalendar

.travis.yml
Recent PRs (#302 #303) have failed on openjdk7 and oraclejdk7 due to [discontinued support for TLS v1.1](https://central.sonatype.org/articles/2018/May/04/discontinued-support-for-tlsv11-and-below/)
I wasn't able to find a way to make sure it uses TLS v1.2, so I upgraded to Trusty. I had to remove oraclejdk7 on Trusty since [oracle JDK 7 is not provided because it reached End of Life in April 2015](https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images)
=> Upgrade to trusty and remove oraclejdk7

src/main/java/com/github/javafaker/Name.java, src/test/java/com/github/javafaker/NameTest.java
Some languages include compound names (spanish and portugese for
example) and that breaks username and email validation.
=> Remove whitespaces from usernames (#296)

src/main/java/com/github/javafaker/Internet.java, src/test/java/com/github/javafaker/InternetTest.java
More info on issue #296 (comment by @gregod).
Please, feel free to suggest any changes :)
=> Strip accents on email address to conform with RFC 5322

src/main/java/com/github/javafaker/DateAndTime.java, src/test/java/com/github/javafaker/DateAndTimeTest.java
Useful when we want a date in the future, specifying a minimum amount of time (like for a renewal date, where someone could want at least 30 days in the future, but 60 days maximum)
=> Generate Dates in future or past with minimum distance from now

src/test/java/com/github/javafaker/MusicTest.java
The regex for genre() method in MusicTest could not cover all the values of genre in en.yml, thus this test randomly fails (when it meets 'Rock and roll', 'Hip-Hop' etc).
I try to fix this random failure by modifying the regex of the matcher.
=> Fix random failure of genre() in MusicTest

src/main/resources/de.yml
Osten does not start with an E!
=> Fix abbreviation for Osten

src/main/java/com/github/javafaker/Internet.java, src/main/resources/en/internet.yml, src/test/java/com/github/javafaker/InternetTest.java
**Added a way to access user_agent values using method calls through `faker.internet()` instead of resolving them through `faker.resolve(...)`.**
Example:
`faker.internet().userAgent(USER_AGENT.CHROME); //returns a CHROME user_agent value.`
**Also, added a way to get a random user_agent value without pre-selecting of browser vendor.**
Example:
`faker.internet().userAgentAny(); //returns a random user_agent value.`
**Increased the number of user_agent values in `internet.yml` file to 10 value for each browser**.
=> Add a convenient way to get USER_AGENT values and add new fake user_agent values, see issue #336

src/test/java/com/github/javafaker/CommerceTest.java, src/test/java/com/github/javafaker/CountryTest.java, src/test/java/com/github/javafaker/WitcherTest.java
by supporting words with dash like "First-Class" in the regex and adding missing characters to few regexes
=> Fix intermittent failing tests

src/main/java/com/github/javafaker/Color.java, src/main/java/com/github/javafaker/service/RandomService.java, src/test/java/com/github/javafaker/ColorTest.java, src/test/java/com/github/javafaker/service/RandomServiceTest.java
Added a way to generate hex string from `faker.random(int length) ` and `faker.color().hex()`, related to issue #282.
**Example usages:**
```
Faker faker = new Faker(); //
System.out.println(faker.random().hex());  // 768AB21E
System.out.println(faker.random().hex(4)); // 820E
System.out.println(faker.color().hex()); // #F78DFE
System.out.println(faker.color().hex(false)); // DC095B No "#" sign.
```
=> Add hex value generation, both for as color and as random, see issue #282

src/main/java/com/github/javafaker/Internet.java, src/main/java/com/github/javafaker/Lorem.java, src/test/java/com/github/javafaker/InternetTest.java, src/test/java/com/github/javafaker/LoremTest.java
Added digit constraints for password generations. Every existing method defaults to "true" for including digits. Exclusion of digits must be explicitly passed as a boolean parameter.
`Internet i = new Faker().internet();`
`System.out.println(i.password(8, 16, false, false));  // Defaults to True => 37fy9bv225`
`System.out.println(i.password(8, 16, false, false, false));  // Exclusion of digits => srklamzltawc`
`System.out.println(i.password()); // Defaults to True => 4lt1juph03hwzq7`
`System.out.println(i.password(true)); //Explicit True => 7dfsikm3aalbq2v`
`System.out.println(i.password(false)); // No digits => irrlhcerfezp`
=> Add digit constraint for passwords, issue #360

src/main/java/com/github/javafaker/service/FakeValuesService.java, src/test/java/com/github/javafaker/LoremTest.java, src/test/java/com/github/javafaker/service/FakeValuesServiceTest.java
There was a trouble to execute expressions with more than 2 args like this
#{Number.randomDouble '2','1','1000'}
Pattern
#\\{([a-z0-9A-Z_.]+)\\s?(?:'([^']+)')?(?:,'([^']+)')*}
determinants just the last one match for group (?:,'([^']+)')*, as a result middle args are missed and wrong directive is built
=> Update arguments parsing from expressions

src/main/java/com/github/javafaker/service/FakeValuesService.java
The normalized locale is never added to the chain of locales.
For fr-CA locale, the fakeValuesList will contains FakeValues with locale in this order [fr-CA, fr-CA, en]
and not the intended [fr-CA, fr, en].
To fix the issue we need to use the variable l from the chain of locales and not the locale value.
=> Bug fix in FakeValuesService setup

pom.xml
This should solve DiUS#470
The discussion here:
https://bitbucket.org/asomov/snakeyaml/issues/377/allow-configuration-for-preventing-billion
A review by a third-party (RedHat) here https://bugzilla.redhat.com/show_bug.cgi?id=1785376
=> Updating snakeyaml to 1.26 to solve #470

src/main/java/com/github/javafaker/DateAndTime.java
When using DateAndTime.birthday(..) it's not obvious that the generated birthday depends on the current day. This leads to the wrong assumption that calling the method with the same random seed creates the same birthday with every call. However, the method produces different results whether it's called in 2020 or 2021.
This PR adds clarification to the method's Javadoc.
=> Clarify documentation of DateAndTime.birthday(..)
