pom.xml
src/main/java/com/github/javafaker/DateAndTime.java
src/main/java/com/github/javafaker/Faker.java
src/main/java/com/github/javafaker/service/RandomService.java
src/test/java/com/github/javafaker/DateAndTimeTest.java
src/test/java/com/github/javafaker/service/RandomServiceTest.java

This pull request adds a new date faker so users can generate random future or past dates or random dates between two dates. Inspired by faker-js [date.js] (https://github.com/Marak/faker.js/blob/master/lib/date.js).
an example usage:
Date withinTwoWeeks = faker.date().future(14, TimeUnit.DAYS);

Add date() faker, a random date generator

---

src/main/java/com/github/javafaker/Address.java

As all yml files contain states it would be nice to call for state name.

Add getter for state to Address.

---

src/main/java/com/github/javafaker/Faker.java
src/main/java/com/github/javafaker/Number.java
src/test/java/com/github/javafaker/NumberTest.java

Number generator

---

pom.xml
src/main/java/com/github/javafaker/Faker.java
src/main/java/com/github/javafaker/Finance.java
src/main/java/com/github/javafaker/service/FakeValuesService.java
src/main/java/com/github/javafaker/service/FakeValuesServiceInterface.java
src/test/java/com/github/javafaker/FakerTest.java
src/test/java/com/github/javafaker/FinanceTest.java

If you do not want to add the Generex dependency I will try to do a implementation.

Add regexify and finance bic

---

src/test/java/com/github/javafaker/integration/FakerIT.java

@codingricky I forgot to add these classes to the integration test when I created them. Sorry.

added App and Commerce to integration test

---

README.md
src/main/java/com/github/javafaker/Faker.java
src/main/java/com/github/javafaker/Shakespeare.java
src/test/java/com/github/javafaker/ShakespeareTest.java
src/test/java/com/github/javafaker/integration/FakerIT.java

I put the quotes directly into the faker like https://github.com/stympy/faker/blob/master/lib/faker/shakespeare.rb so that the faker locale.ymls can be easily reused.

added Shakespeare

---

pom.xml
src/main/java/com/github/javafaker/service/FakeValuesService.java
src/main/java/com/github/javafaker/service/RandomService.java
src/test/java/com/github/javafaker/FakerTest.java

update to generex version to 1.0.0 to make this possible

regexify should use seed

---

src/test/java/com/github/javafaker/IdNumberTest.java

fixex IdNumberTest#testInvalid regular expression

---

src/test/java/com/github/javafaker/EducatorTest.java

Sorry about that. I just copied the regular expressions of the faker test, without any in-depth testing.

fixed EducatorTest regular expressions

---

src/main/java/com/github/javafaker/Name.java
src/test/java/com/github/javafaker/NameTest.java

implemented username() method that returns username depending on first and last name

implemented username() method 

---

README.md
src/main/java/com/github/javafaker/Cat.java
src/main/java/com/github/javafaker/Faker.java
src/test/java/com/github/javafaker/CatTest.java
src/test/java/com/github/javafaker/integration/FakerIT.java

implemented Cat object

---

src/main/java/com/github/javafaker/Faker.java
src/main/java/com/github/javafaker/service/FakeValuesService.java
src/main/java/com/github/javafaker/service/FakeValuesServiceInterface.java
src/test/java/com/github/javafaker/FakerTest.java

add overloaded method to specify upper case letters

---

pom.xml
src/main/java/com/github/javafaker/Commerce.java
src/main/java/com/github/javafaker/Company.java
src/main/java/com/github/javafaker/Faker.java
src/main/java/com/github/javafaker/Finance.java
src/main/java/com/github/javafaker/Internet.java
src/main/java/com/github/javafaker/Lorem.java
src/main/java/com/github/javafaker/Name.java
src/main/java/com/github/javafaker/service/RandomService.java

Updated dependency; modified classes as needed; changed `RandomService` to use `Random` directly
Addresses issue #116

Updated to commons-lang3

---

src/main/java/com/github/javafaker/Internet.java
src/test/java/com/github/javafaker/InternetTest.java
src/test/java/com/github/javafaker/matchers/CountOfCharactersMatcher.java

Closes DiUS/java-faker#122
Generate fake IP addresses and MAC addresses.  The location (Internet) of the methods
was taken from the stympy/faker project.  Most of the tests and code were ported from
there as well.

Add IPV4, V6 and MAC Addresses to Internet

---

src/main/java/com/github/javafaker/Name.java

Add javadoc for Name

---

pom.xml

Update coveralls plugin to 4.3.0

---

src/main/java/com/github/javafaker/Internet.java
src/test/java/com/github/javafaker/InternetTest.java

safeEmailAddress was simply delegating to emailAddress which was not using
internet.safe_email as I assume it was intended.
it now uses internet.safe_email

Fix safeEmailAddress to use internet.safe_email

---

pom.xml
src/main/java/com/github/javafaker/service/FakeValuesService.java
src/test/java/com/github/javafaker/CryptoTest.java
src/test/java/com/github/javafaker/service/FakeValuesServiceTest.java
src/test/java/com/github/javafaker/service/RandomServiceTest.java

This PR is a little hodge podge, but it's a minor improvement for fake value service messaging.  There are also a few more tests to improve coverage.

Ensure error messages are useful

---

pom.xml
src/test/java/com/github/javafaker/CryptoTest.java

Remove PowerMock dependency as it does not work with Mockito 2. 
Remove CryptoTest#missingAlgorithVomitsHorribly which was the only test using PowerMock did not really test anything anyway.

update Mockito version to 2.2.6

---

src/main/java/com/github/javafaker/Company.java
src/main/java/com/github/javafaker/Internet.java
src/main/java/com/github/javafaker/service/FakeValuesService.java
src/main/java/com/github/javafaker/service/FakerIDN.java
src/test/java/com/github/javafaker/FoodTest.java
src/test/java/com/github/javafaker/integration/FakerIT.java
src/test/java/com/github/javafaker/service/FakeValuesServiceTest.java

demonstrates https://github.com/DiUS/java-faker/issues/148 occurs for other locales and other methods

extend integration tests to cover all locales with a yml file

---

src/main/java/com/github/javafaker/Faker.java
src/main/java/com/github/javafaker/File.java
src/main/java/com/github/javafaker/Internet.java
src/main/java/com/github/javafaker/service/FakeValuesService.java
src/main/java/com/github/javafaker/service/FakerIDN.java
src/test/java/com/github/javafaker/AbstractFakerTest.java
src/test/java/com/github/javafaker/AddressTest.java
src/test/java/com/github/javafaker/FileTest.java
src/test/java/com/github/javafaker/InternetTest.java
src/test/java/com/github/javafaker/integration/FakerIT.java
src/test/java/com/github/javafaker/repeating/Repeat.java
src/test/java/com/github/javafaker/repeating/RepeatRule.java

Added File to faker (ported from stympy/faker)
Also, added a test repeater borrowed from https://gist.github.com/fappel/8bcb2aea4b39ff9cfb6e
Updated Internet with slug() (implementation ported from stympy/faker)

Add File to Faker from stympy/faker

---

README.md
src/main/java/com/github/javafaker/Faker.java
src/main/java/com/github/javafaker/Pokemon.java
src/test/java/com/github/javafaker/PokemonTest.java
src/test/java/com/github/javafaker/integration/FakerIT.java

a really essential addition ;)

add Pokemon

---

src/test/java/com/github/javafaker/CodeTest.java

let ISBNValidator test ISBN-10 codes directly (do not convert to ISBN-13 codes before validation)

use ISBNValidator in isbn(10|13)DefaultIsNoSeparator tests

---

README.md
src/main/java/com/github/javafaker/Ancient.java
src/main/java/com/github/javafaker/Faker.java
src/test/java/com/github/javafaker/AncientTest.java
src/test/java/com/github/javafaker/integration/FakerIT.java

requires https://github.com/DiUS/java-faker/pull/183

add Ancient

---

src/main/java/com/github/javafaker/GameOfThrones.java
src/test/java/com/github/javafaker/GameOfThronesTest.java

requires https://github.com/DiUS/java-faker/pull/183

add GameOfThrones#dragon

---

src/main/java/com/github/javafaker/Finance.java
src/main/java/com/github/javafaker/service/FakeValuesService.java
src/test/java/com/github/javafaker/NumberTest.java

- replace obvious forindex with for each statements
- add uppercase 'L' to long literals
- remove redundant `.toString()` call on String object

Improve readability of code

---

src/main/java/com/github/javafaker/Lorem.java
src/test/java/com/github/javafaker/LoremTest.java

replicates the behavior of (ruby) faker
allows generation of sentences with a fixed number of words

add Lorem#sentence(int wordCount, int randomWordsToAdd) (fixes #190)

---

src/test/java/com/github/javafaker/AncientTest.java

fixes https://travis-ci.org/DiUS/java-faker/jobs/197797494

AncientTest#hero: fix regular expression

---

src/main/java/com/github/javafaker/Music.java
src/test/java/com/github/javafaker/MusicTest.java

similar to https://github.com/stympy/faker/commit/7a44e6c36b47bb63bc56fc6fba2b8501edcae69e

add Music#chord

---

src/main/java/com/github/javafaker/DateAndTime.java
src/test/java/com/github/javafaker/DateAndTimeTest.java

@codingricky As requested in #208, here is the pull request.
Unfortunately I couldn't take advantage of Java 8's LocaDateTime as the compilation target is Java 1.6.

Add birthday generator

---

src/main/java/com/github/javafaker/service/RandomService.java
src/test/java/com/github/javafaker/service/RandomServiceTest.java

This PR adds methods to select random elements from arrays, collections or enumerations.
Fixes https://github.com/DiUS/java-faker/issues/211

Add support for random collection element selection

---

src/main/java/com/github/javafaker/Faker.java
src/main/java/com/github/javafaker/LordOfTheRings.java
src/test/java/com/github/javafaker/LordOfTheRingsTest.java
src/test/java/com/github/javafaker/integration/FakerIT.java

`LordOfTheRings` class added with `character` and `location` methods supported.

Add support for lord_of_the_rings

---

README.md
src/main/java/com/github/javafaker/Faker.java
src/main/java/com/github/javafaker/HarryPotter.java
src/test/java/com/github/javafaker/HarryPotterTest.java
src/test/java/com/github/javafaker/integration/FakerIT.java

Added `HarryPotter` class with `book`, `character`, `location` and `quote` methods supported.
Updated README with: LordOfTheRings, Zelda and HarryPotter.

Add HarryPotter and update README

---

README.md
src/main/java/com/github/javafaker/Esports.java
src/main/java/com/github/javafaker/Faker.java
src/test/java/com/github/javafaker/EsportsTest.java
src/test/java/com/github/javafaker/integration/FakerIT.java

Added Esports class with `player`, `team`, `event`, `league` and `game` methods supported.

Add Esports class

---

README.md
src/main/java/com/github/javafaker/Faker.java
src/main/java/com/github/javafaker/Friends.java
src/test/java/com/github/javafaker/FriendsTest.java
src/test/java/com/github/javafaker/integration/FakerIT.java

Added `Friends` class with `character`, `location, and `quote, methods supported.

Add Friends class

---

README.md
src/main/java/com/github/javafaker/Faker.java
src/main/java/com/github/javafaker/Hipster.java
src/test/java/com/github/javafaker/HipsterTest.java
src/test/java/com/github/javafaker/integration/FakerIT.java

Adding `Hipster` class with `word` method supported.

Add Hipster

---

README.md
src/main/java/com/github/javafaker/Faker.java
src/main/java/com/github/javafaker/TwinPeaks.java
src/test/java/com/github/javafaker/TwinPeaksTest.java
src/test/java/com/github/javafaker/integration/FakerIT.java

Added `TwinPeaks` class with `character`, `location` and `quote` methods supported.

Add TwinPeaks

---

README.md
src/main/java/com/github/javafaker/Faker.java
src/main/java/com/github/javafaker/RickAndMorty.java
src/test/java/com/github/javafaker/RickAndMortyTest.java
src/test/java/com/github/javafaker/integration/FakerIT.java

Added `RickAndMorty` class with `location`, `character` and `quote` methods supported.

Add RickAndMorty

---

src/main/java/com/github/javafaker/Faker.java
src/test/java/com/github/javafaker/FakerTest.java

Issue: #236
Not sure about tests, however I expect to get a `Faker` instance by the end of the day. The internals of it are tested elsewhere.

Can acquire Faker instance via static utility methods. Fixes #236

---

src/main/java/com/github/javafaker/service/FakeValuesService.java

Hi,
This pull request keeps previous behaviour (i.e. logging the error) but avoids a potential NPE. Trivial, but may be worth?
Thanks!
Bruno

Avoid potential NPE

---

README.md

forgot to update the readme with my last pull request

README.md: add en-MS locale

---

README.md
src/main/java/com/github/javafaker/Avatar.java
src/main/java/com/github/javafaker/Faker.java
src/test/java/com/github/javafaker/AvatarTest.java
src/test/java/com/github/javafaker/InternetTest.java

This adds support for getting random avatar urls:
```
String avatar = faker.avatar().image(); // avatar: https://s3.amazonaws.com/uifaces/faces/twitter/cofla/128.jpg
```

Add support for random avatar urls

---

README.md

Because life is too short for googling! :)

Add link to Ruby's faker gem repository

---

src/main/java/com/github/javafaker/Options.java
src/test/java/com/github/javafaker/OptionsTest.java

- Receiving and returning generic type in Options#option
- Add and fix javadoc's

Options#option receive and return generic varargs

---

src/main/java/com/github/javafaker/Music.java
src/main/resources/en.yml
src/test/java/com/github/javafaker/MusicTest.java

Add genre to music faker class

Add genre to music faker class

---

src/main/java/com/github/javafaker/service/FakeValues.java
src/main/java/com/github/javafaker/service/FakeValuesGrouping.java
src/main/java/com/github/javafaker/service/FakeValuesInterface.java
src/main/java/com/github/javafaker/service/FakeValuesService.java
src/main/java/com/github/javafaker/service/LocaleDoesNotExistException.java
src/main/java/com/github/javafaker/service/files/EnFile.java
src/test/java/com/github/javafaker/service/FakeValuesGroupingTest.java
src/test/java/com/github/javafaker/service/FakeValuesServiceTest.java
src/test/java/com/github/javafaker/service/FakeValuesTest.java

lazy loading to improve performance

Performance

---

src/main/java/com/github/javafaker/service/FakeValuesService.java
src/test/java/com/github/javafaker/service/FakeValuesServiceTest.java

Currently date cannot be used in expressions, this enhancement will allow that

Added support for date expressions like #{date.future '10','TimeUnit.DAYS'}

---

src/main/java/com/github/javafaker/BackToTheFuture.java
src/main/java/com/github/javafaker/Faker.java
src/test/java/com/github/javafaker/BackToTheFutureTest.java
src/test/java/com/github/javafaker/integration/FakerIT.java

Added classes for BackToTheFuture and BackToTheFutureTest. 
Added BackToTheFuture to Faker constructor and necessary variable (not in alphabetical order).

BackToTheFuture

---

src/main/java/com/github/javafaker/Country.java
src/test/java/com/github/javafaker/CountryTest.java

Adds `name()` method to `Country` class

add country name

---

src/main/java/com/github/javafaker/ElderScrolls.java
src/main/java/com/github/javafaker/Faker.java
src/test/java/com/github/javafaker/ElderScrollsTest.java

Added elder scrolls as a new random feature. All unit tests passed.

Added elder scrolls

---

src/main/java/com/github/javafaker/ElderScrolls.java
src/main/java/com/github/javafaker/Faker.java
src/main/resources/en/elder_scrolls.yml
src/test/java/com/github/javafaker/ElderScrollsTest.java

Elder scrolls quote

---

README.md
src/main/java/com/github/javafaker/AquaTeenHungerForce.java
src/main/java/com/github/javafaker/Faker.java
src/test/java/com/github/javafaker/AquaTeenHungerForceTest.java
src/test/java/com/github/javafaker/integration/FakerIT.java

Add a faker for AquaTeenHungerForce characters

add AquaTeenHungerForce faker

---

src/main/java/com/github/javafaker/service/FakeValuesService.java

I did not try on standard jvm but that change is fixing https://github.com/DiUS/java-faker/issues/440

Fixed regex on Android

---

src/main/java/com/github/javafaker/Faker.java
src/main/java/com/github/javafaker/ProgrammingLanguage.java
src/main/resources/hu.yml
src/test/java/com/github/javafaker/NumberTest.java
src/test/java/com/github/javafaker/ProgrammingLanguageTest.java
src/test/java/com/github/javafaker/integration/FakerIT.java

Add `ProgrammingLanguage` faker class

Add programming language

---

src/main/java/com/github/javafaker/Faker.java

To permit discrimination/variation of the values Faker provides.
All 636 tests have been executed and pass.

Support injection of FakeValuesService

---

src/test/java/com/github/javafaker/service/FakeValuesServiceTest.java

FakeValuesServiceTest fails when run in workspace with Locale other than en

fix FakeValuesServiceTest / pastDate + futureDate for local test

---

src/main/java/com/github/javafaker/DateAndTime.java
src/test/java/com/github/javafaker/DateAndTimeTest.java

Because it is UI tests sometimes failed with incorrect date
For exapmle: now 2019-11-21
birthday(23, 65) returns 1996-11-26
It is wrong because for birthday 1996-11-26 it is 22 years old now. Not 23

Fix birthday(): add currentMonth and currentDay 

---

README.md
src/main/java/com/github/javafaker/Coin.java
src/main/java/com/github/javafaker/Faker.java
src/main/resources/en/coin.yml
src/test/java/com/github/javafaker/CoinTest.java
src/test/java/com/github/javafaker/integration/FakerIT.java

I've added a new Coin class, tests, updating README.md.
Fixes issue #481

Added new Coin class

---

README.md
src/main/java/com/github/javafaker/Basketball.java
src/main/java/com/github/javafaker/Faker.java
src/main/java/com/github/javafaker/service/files/EnFile.java
src/test/java/com/github/javafaker/BasketballTest.java
src/test/java/com/github/javafaker/integration/FakerIT.java

Fix #482 
My teammate PR is https://github.com/DiUS/java-faker/pull/503
Acutally the yml of basketball has existed in resource, we just did part of it.

Fix Basketball feature

---

src/test/java/com/github/javafaker/DateAndTimeTest.java
src/test/java/com/github/javafaker/InternetTest.java
src/test/java/com/github/javafaker/service/FakeValuesServiceTest.java
src/test/java/com/github/javafaker/service/FakeValuesTest.java
src/test/java/com/github/javafaker/service/RandomServiceTest.java

Fix #533 
Adding some test cases for public method to increase the coverage. But still cannot increase coverage for private methods.

Add some test cases to increase coverage

---

README.md
src/main/java/com/github/javafaker/Faker.java
src/main/java/com/github/javafaker/Gender.java
src/main/resources/en/gender.yml
src/test/java/com/github/javafaker/GenderTest.java
src/test/java/com/github/javafaker/integration/FakerIT.java

Fixed issue 468

---

src/main/java/com/github/javafaker/Barcode.java
src/main/java/com/github/javafaker/Faker.java
src/main/java/com/github/javafaker/service/files/En.java
src/main/resources/en/barcode.yml
src/test/java/com/github/javafaker/BarcodeTest.java

This faker generate barcode with different types and data.

Add a Barcode fake generator

---

src/main/java/com/github/javafaker/service/RandomService.java

The current implementation allocates a new array of hex constants every time the method is called, and it uses a `StringBuilder` when the length of the final result is known. Seems like an easy win to me.

More efficient hex generation

---

README.md
src/main/java/com/github/javafaker/Faker.java
src/main/java/com/github/javafaker/Sip.java
src/main/java/com/github/javafaker/service/files/EnFile.java
src/main/resources/en/sip.yml
src/test/java/com/github/javafaker/SipTest.java

Added faker class, yaml configuration file, and test cases for generating sip data.

feature: added sip data generator.

---

src/test/java/com/github/javafaker/StarCraftTest.java

Fix issue 575. Apostrophe added to regex in StarCraftTest
